meta_product_name: "Nom du Product"
meta_title: "Nom du Product - Tagline du Product"
meta_description: "Description percutante"
meta_image: "image.jpg"                           # Une image dans votre dossier app/assets/images/
twitter_account: "@nomdevotrecompte"              # indispensable pour les Twitter Cards
