# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7578e6f1e4871902da9e943492bbe1ff06c400fdbb1e39129c83c9cfa1661e8c8b09b06e32a17a6d7d898d62333800f92aeb107698ac89854421c963b2f5fdbe

test:
  secret_key_base: d41f6472ae40452bd597fc5fc0b7c4c69bec160146f970ce14e68d1a81fe4d4c32d9b9fd324b68c3971b821e407c8ddf17e06d8a548483f4cc04c842a8aa6212

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
